import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2 } from "lucide-react";
import { adminApi, type EventInput } from "@/api/admin.api";
import { getErrorMessage } from "@joe-wilson/shared/lib/errors";

const blank:EventInput={title:"",description:"",location:"",eventDate:"",isPublished:false};
function EventForm({initial,label,pending,onSubmit}:{initial:EventInput;label:string;pending:boolean;onSubmit:(input:EventInput)=>void}){const [item,setItem]=useState(initial);return <form onSubmit={e=>{e.preventDefault();onSubmit({...item,eventDate:new Date(item.eventDate).toISOString()});}} className="bg-white border p-5 grid md:grid-cols-2 gap-3"><input required value={item.title} onChange={e=>setItem({...item,title:e.target.value})} className="border p-3" placeholder="Event title"/><input type="datetime-local" required value={item.eventDate ? item.eventDate.slice(0,16) : ""} onChange={e=>setItem({...item,eventDate:e.target.value})} className="border p-3"/><input value={item.location??""} onChange={e=>setItem({...item,location:e.target.value})} className="border p-3" placeholder="Location"/><label className="flex items-center gap-2"><input type="checkbox" checked={item.isPublished} onChange={e=>setItem({...item,isPublished:e.target.checked})}/>Publish in footer</label><textarea value={item.description??""} onChange={e=>setItem({...item,description:e.target.value})} className="md:col-span-2 border p-3 min-h-24" placeholder="Description (optional)"/><button disabled={pending} className="justify-self-end bg-brand px-5 py-3 text-white">{label}</button></form>}
export default function EventsPage(){const qc=useQueryClient();const q=useQuery({queryKey:["admin","events"],queryFn:adminApi.events});const create=useMutation({mutationFn:adminApi.createEvent,onSuccess:()=>qc.invalidateQueries({queryKey:["admin","events"]})});const update=useMutation({mutationFn:({id,input}:{id:string;input:EventInput})=>adminApi.updateEvent(id,input),onSuccess:()=>qc.invalidateQueries({queryKey:["admin","events"]})});const remove=useMutation({mutationFn:adminApi.deleteEvent,onSuccess:()=>qc.invalidateQueries({queryKey:["admin","events"]})});const error=q.error||create.error||update.error||remove.error;return <div className="p-5 lg:p-7 max-w-[1100px] mx-auto space-y-6"><div><p className="text-[11px] font-bold text-brand uppercase">Public content</p><h1 className="text-3xl font-bold">Events</h1><p className="text-sm text-gray-500">Published future events appear in the website footer.</p></div>{error&&<p className="bg-red-50 p-3 text-red-700">{getErrorMessage(error)}</p>}{q.isPending?<p>Loading events…</p>:<div className="space-y-4">{q.data?.map(record=><div key={record.id}><EventForm initial={record} pending={update.isPending} onSubmit={input=>update.mutate({id:record.id,input})} label="Save event"/><button onClick={()=>confirm(`Delete ${record.title}?`)&&remove.mutate(record.id)} className="mt-2 text-red-600 flex gap-1 text-sm"><Trash2 size={14}/>Delete event</button></div>)}</div>}<section><h2 className="font-semibold mb-3 flex gap-2"><Plus size={17}/>Add event</h2><EventForm initial={blank} pending={create.isPending} onSubmit={input=>create.mutate(input)} label="Create event"/></section></div>}
