import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Plus, Search, Trash2 } from "lucide-react";
import { adminApi, type MasterclassInput } from "@/api/admin.api";
import { getErrorMessage } from "@joe-wilson/shared/lib/errors";

const blank:MasterclassInput={title:"",description:"",coverImageUrl:"",priceCents:0,status:"draft",startsAt:"",endsAt:"",isPublished:false};
export default function MasterclassesPage(){
  const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [draft,setDraft]=useState<MasterclassInput>(blank); const qc=useQueryClient();
  const query=useQuery({queryKey:["admin","masterclasses"],queryFn:adminApi.masterclasses});
  const create=useMutation({mutationFn:adminApi.createMasterclass,onSuccess:()=>{setOpen(false);setDraft(blank);qc.invalidateQueries({queryKey:["admin","masterclasses"]})}});
  const remove=useMutation({mutationFn:adminApi.deleteMasterclass,onSuccess:()=>qc.invalidateQueries({queryKey:["admin","masterclasses"]})});
  const list=(query.data??[]).filter(item=>item.title.toLowerCase().includes(search.toLowerCase())); const error=query.error||create.error||remove.error;
  return <div className="p-5 lg:p-7 max-w-[1280px] mx-auto space-y-6"><div className="flex justify-between gap-4"><div><p className="text-[11px] font-bold text-brand uppercase tracking-widest">Programs</p><h1 className="text-3xl font-bold">Masterclasses</h1><p className="text-sm text-gray-500">These records feed the public catalogue and members area.</p></div><button onClick={()=>setOpen(true)} className="self-start bg-brand text-white px-5 py-3 flex gap-2"><Plus size={16}/>New masterclass</button></div>{error&&<p role="alert" className="bg-red-50 text-red-700 p-3">{getErrorMessage(error)}</p>}<label className="relative block max-w-sm"><Search size={15} className="absolute left-3 top-3.5 text-gray-400"/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full border pl-9 p-3" placeholder="Search masterclasses"/></label>{query.isPending?<p>Loading masterclasses…</p>:list.length===0?<div className="border border-dashed p-16 text-center text-gray-500">No masterclasses yet. Create the first real program.</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{list.map(item=><article key={item.id} className="bg-white border overflow-hidden">{item.coverImageUrl?<img src={item.coverImageUrl} alt="" className="w-full h-48 object-cover"/>:<div className="w-full h-48 bg-gray-100 grid place-items-center text-gray-400">No cover image</div>}<div className="p-5"><span className="text-xs uppercase text-brand">{item.status}</span><h2 className="text-lg font-semibold mt-1">{item.title}</h2><p className="text-sm text-gray-500 line-clamp-2 mt-2">{item.description||"No description"}</p><div className="flex justify-between mt-4 text-sm"><span>{item.sessionsCount??0} sessions · {item.enrollmentsCount??0} enrolled</span><strong>{new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(item.priceCents/100)}</strong></div><div className="flex gap-3 mt-5"><Link to={`/admin/masterclasses/${item.id}`} className="text-brand font-semibold">Open</Link><button onClick={()=>confirm(`Delete ${item.title}?`)&&remove.mutate(item.id)} className="text-red-600 flex gap-1"><Trash2 size={14}/>Delete</button></div></div></article>)}</div>}
  {open&&<div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-4"><form onSubmit={e=>{e.preventDefault();create.mutate({...draft,priceCents:Number(draft.priceCents)})}} className="bg-white w-full max-w-xl p-6 grid md:grid-cols-2 gap-4"><h2 className="md:col-span-2 text-xl font-bold">Create masterclass</h2><input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} className="border p-3" placeholder="Title"/><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as MasterclassInput["status"]})} className="border p-3"><option value="draft">Draft</option><option value="upcoming">Upcoming</option><option value="active">Active</option><option value="completed">Completed</option></select><textarea required value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="md:col-span-2 border p-3" placeholder="Description"/><input type="url" value={draft.coverImageUrl} onChange={e=>setDraft({...draft,coverImageUrl:e.target.value})} className="md:col-span-2 border p-3" placeholder="Cover image URL from Media Library"/><label className="text-sm">Price (cents)<input type="number" min="0" required value={draft.priceCents} onChange={e=>setDraft({...draft,priceCents:Number(e.target.value)})} className="block w-full border p-3 mt-1"/></label><label className="text-sm">Starts at<input required type="datetime-local" onChange={e=>setDraft({...draft,startsAt:e.target.value?new Date(e.target.value).toISOString():""})} className="block w-full border p-3 mt-1"/></label><label className="text-sm">Ends at<input required type="datetime-local" onChange={e=>setDraft({...draft,endsAt:e.target.value?new Date(e.target.value).toISOString():""})} className="block w-full border p-3 mt-1"/></label><label className="flex items-center gap-2"><input type="checkbox" checked={draft.isPublished} onChange={e=>setDraft({...draft,isPublished:e.target.checked})}/>Publish on website</label><div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="border px-5 py-3">Cancel</button><button disabled={create.isPending} className="bg-brand text-white px-5 py-3">{create.isPending?"Creating…":"Create"}</button></div></form></div>}</div>;
}
