import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Save, Trash2 } from "lucide-react";
import { adminApi, type SettingsMap, type Testimonial, type TestimonialInput } from "@/api/admin.api";
import { getErrorMessage } from "@joe-wilson/shared/lib/errors";

const blank: TestimonialInput = { authorName: "", authorOrg: "", quote: "", avatarUrl: "", isFeatured: true, orderIndex: 0 };
const fields = [["contact_email","General email"],["booking_email","Booking email"],["contact_phone_1","Phone"],["contact_location","Location"],["social_instagram","Instagram URL"],["social_facebook","Facebook URL"],["social_youtube","YouTube URL"]] as const;

export default function SettingsPage() {
  const qc=useQueryClient(); const [tab,setTab]=useState<"contact"|"testimonials">("contact"); const [settings,setSettings]=useState<SettingsMap>({}); const [items,setItems]=useState<Testimonial[]>([]); const [next,setNext]=useState<TestimonialInput>(blank); const [message,setMessage]=useState("");
  const sq=useQuery({queryKey:["admin","settings"],queryFn:adminApi.settings}); const tq=useQuery({queryKey:["testimonials"],queryFn:adminApi.testimonials});
  useEffect(()=>{if(sq.data)setSettings(sq.data)},[sq.data]); useEffect(()=>{if(tq.data)setItems(tq.data)},[tq.data]);
  const saveSettings=useMutation({mutationFn:adminApi.updateSettings,onSuccess:data=>{setSettings(data);setMessage("Public settings saved.");qc.invalidateQueries({queryKey:["admin","settings"]})}});
  const saveItem=useMutation({mutationFn:({id,input}:{id?:string;input:TestimonialInput})=>id?adminApi.updateTestimonial(id,input):adminApi.createTestimonial(input),onSuccess:()=>{setNext(blank);setMessage("Testimonial saved.");qc.invalidateQueries({queryKey:["testimonials"]})}});
  const remove=useMutation({mutationFn:adminApi.deleteTestimonial,onSuccess:()=>qc.invalidateQueries({queryKey:["testimonials"]})});
  const error=sq.error||tq.error||saveSettings.error||saveItem.error||remove.error;
  const change=(id:string,key:keyof TestimonialInput,value:string|number|boolean)=>setItems(list=>list.map(item=>item.id===id?{...item,[key]:value}:item));
  return <div className="p-5 lg:p-7 max-w-[1100px] mx-auto space-y-6 pb-16"><div><p className="text-[11px] font-bold text-brand uppercase tracking-widest">Public content</p><h1 className="text-3xl font-bold">Settings</h1><p className="text-sm text-gray-500">Changes here feed the public website through the API.</p></div><div className="flex border-b"><button onClick={()=>setTab("contact")} className={`px-5 py-3 ${tab==="contact"?"border-b-2 border-brand text-brand":""}`}>Contact & social</button><button onClick={()=>setTab("testimonials")} className={`px-5 py-3 ${tab==="testimonials"?"border-b-2 border-brand text-brand":""}`}>Testimonials</button></div>{message&&<p role="status" className="bg-emerald-50 text-emerald-700 p-3">{message}</p>}{error&&<p role="alert" className="bg-red-50 text-red-700 p-3">{getErrorMessage(error)}</p>}
  {tab==="contact"?<form onSubmit={e=>{e.preventDefault();setMessage("");saveSettings.mutate(settings)}} className="bg-white border p-6 grid md:grid-cols-2 gap-5">{fields.map(([key,label])=><label key={key} className="text-sm">{label}<input value={settings[key]??""} onChange={e=>setSettings({...settings,[key]:e.target.value})} className="mt-2 w-full border p-3"/></label>)}<div className="md:col-span-2"><button disabled={saveSettings.isPending} className="inline-flex gap-2 items-center bg-brand text-white px-5 py-3"><Save size={16}/>{saveSettings.isPending?"Saving…":"Save public settings"}</button></div></form>:<div className="space-y-5">{tq.isPending&&<p>Loading testimonials…</p>}{items.map(item=><form key={item.id} onSubmit={e=>{e.preventDefault();saveItem.mutate({id:item.id,input:item})}} className="bg-white border p-5 grid md:grid-cols-2 gap-4"><input required aria-label="Author name" value={item.authorName} onChange={e=>change(item.id,"authorName",e.target.value)} className="border p-3" placeholder="Author name"/><input value={item.authorOrg??""} onChange={e=>change(item.id,"authorOrg",e.target.value)} className="border p-3" placeholder="Role or organisation"/><textarea required value={item.quote} onChange={e=>change(item.id,"quote",e.target.value)} className="md:col-span-2 border p-3" placeholder="Testimonial"/><input value={item.avatarUrl??""} onChange={e=>change(item.id,"avatarUrl",e.target.value)} className="border p-3" placeholder="Avatar URL"/><label className="flex items-center gap-2"><input type="checkbox" checked={item.isFeatured} onChange={e=>change(item.id,"isFeatured",e.target.checked)}/>Featured</label><div className="md:col-span-2 flex gap-3"><button className="bg-brand text-white px-4 py-2">Save</button><button type="button" onClick={()=>confirm("Delete this testimonial?")&&remove.mutate(item.id)} className="border text-red-600 px-4 py-2 inline-flex gap-2"><Trash2 size={15}/>Delete</button></div></form>)}<form onSubmit={e=>{e.preventDefault();saveItem.mutate({input:{...next,orderIndex:items.length}})}} className="bg-gray-50 border border-dashed p-5 grid md:grid-cols-2 gap-4"><h2 className="md:col-span-2 font-semibold flex gap-2"><Plus size={18}/>Add testimonial</h2><input required value={next.authorName} onChange={e=>setNext({...next,authorName:e.target.value})} className="border p-3" placeholder="Author name"/><input value={next.authorOrg} onChange={e=>setNext({...next,authorOrg:e.target.value})} className="border p-3" placeholder="Role or organisation"/><textarea required value={next.quote} onChange={e=>setNext({...next,quote:e.target.value})} className="md:col-span-2 border p-3" placeholder="Testimonial"/><input value={next.avatarUrl} onChange={e=>setNext({...next,avatarUrl:e.target.value})} className="border p-3" placeholder="Avatar URL"/><button className="bg-brand text-white p-3">Add testimonial</button></form></div>}</div>;
}
